### ISSUE TITLE
[Feature Request] Allow additional emoji reactions

### ISSUE THREAD

**Issue by Shwaffle** [sillvva/rpg-schedule#107]
In our community we have different sections for different games, one of them being Destiny 2. We utilize RPG Schedule to form raids, and in this game there are multiple raids that people like to run. Due to this we have a "Player Choice" once a week and have voting to help that process. 

Currently, we have to create a second post with the voting which you can see here: https://i.imgur.com/bM1nHZz.png. I am wondering if there is a possibility of having this within the raid post itself but RPG Schedule removes all additional emoji's when reacting to it. I did try modifying the bots permissions to block it from deleting the emojis but it broke the rest of the bots functionality so it was reverted.

**Comment by sillvva** [comment]
I have pushed an update to allow additional reactions.
