### ISSUE TITLE
Session Reminder "When" always shows "Starting in 0 minutes"

### ISSUE THREAD

**Issue by Mephi-Dross** [sillvva/rpg-schedule#111]
**Issue**
After creating a new game and setting the reminder, the bot posts in the discord channel with said reminder. The "When" field for said bot message is supposed to be filled with the reminder (e.g. in 1 hour, in 30 minutes, etc.). Instead it always says "Starting in 0 minutes"

**Desired Outcome**
Bot message contains the correct reminder time.

**Additional Info**
See attached screenshots for examples. Names redacted for privacy, except mine. Feel free to send me a message on discord if clarification is required.
![Issue01](https://user-images.githubusercontent.com/5930357/69905629-db278f80-13b6-11ea-91fa-e552decb3b64.jpg)
![Issue02](https://user-images.githubusercontent.com/5930357/69905630-db278f80-13b6-11ea-849d-4af1be75d15b.jpg)

**Comment by sillvva** [comment]
This has been fixed. Thanks for the heads up!
