### ISSUE TITLE
Error connecting to db: failed to connect to server [localhost:27017] 

### ISSUE THREAD

**Issue by sojohnnysaid** [sillvva/rpg-schedule#153]
I'm running the bot locally but i'm passing in my heroku/mlab mongodb uri to connect to their cloud db. Using the MONGODB_URL in .env and getting this error message:

Error: Error connecting to db: failed to connect to server [localhost:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017]

**Comment by sojohnnysaid** [comment]
also this in the error message at the top:
express-session deprecated req.secret; provide secret option app/index.js:90:34
(node:7104) UnhandledPromiseRejectionWarning: Error: An invalid token was provided.
    at /Users/home/Desktop/rpg-schedule/node_modules/discord.js/src/client/rest/RESTMethods.js:34:54

**Comment by sillvva** [comment]
Sorry for the late response. I've updated the local development instructions.

**Comment by sojohnnysaid** [comment]
thanks!

**Comment by sojohnnysaid** [comment]
Also I tried going to your website but the link was broken on your profile. Thanks again.
