### ISSUE TITLE
[Feature Request] Clear Reserved List on Recurring Games

### ISSUE THREAD

**Issue by ehsawyer** [sillvva/rpg-schedule#157]
**Is your feature request related to a problem? Please describe.**
My group and I schedule games every few days. I used to do this manually until you added the feature for recurring games. The recurring games feature made it a lot faster, but I still have to clear the reserved list each night once the game reschedules itself.

**Describe the solution you'd like**
Is it possible to add a checkbox in the Frequency section that has it clear the reserved list after every game?

**Comment by sillvva** [comment]
Good idea! I will have that available soon.

**Comment by ehsawyer** [comment]
Thank you! I just wanna say thank you for making this! It's made scheduling our games so much easier.
