### ISSUE TITLE
[command issue] !schedule configuration

### ISSUE THREAD

**Issue by kaliuser8** [sillvva/rpg-schedule#191]
Hello,
I type !schedule configuration, but nothing happens.

Thank you
kaliuser8

**Comment by Level8Broccoli** [comment]
_Can confirm in German and German (Switzerland)._

If I change to languages `ch` or `de` (which I provided; If it is my mistake, please tell me how I can fix it), I have no longer access to the *Schedule Help* command list via the `!schedule` command. All the other languages seemed to work properly.

_Example English_
![image](https://user-images.githubusercontent.com/7040739/77915674-28017100-7298-11ea-9a77-5b81fd609cef.png)

_Example German_
![image](https://user-images.githubusercontent.com/7040739/77915682-2a63cb00-7298-11ea-8154-aae1c2508858.png)

**Comment by sillvva** [comment]
Hi, sorry for the late reply. It seems, in other languages, the help text has started to exceed the maximum character limit for a single discord post. I can fix that by having it send 2-3 posts instead. I will push a fix out shortly.

In the meantime, you can access the same information here:
https://www.rpg-schedule.com/info/about

**Comment by sillvva** [comment]
Update has been deployed, tested, and verified. The command should be working again.
