### ISSUE TITLE
[remove role and manager-role] New commands

### ISSUE THREAD

**Issue by kaliuser8** [sillvva/rpg-schedule#192]
I can add roles and manager-roles, but can't remove them.
I would like you add new commads to do it, if they don't exist (I can't find them in the readme).

Thank you
kaliuser8

**Comment by sillvva** [comment]
Hi, sorry for the late reply. It's been a pretty busy week.

To remove a role, just leave it blank after the command name.

For example:

```
!schedule role
!schedule manager-role
```
