### ISSUE TITLE
invalid user bug

### ISSUE THREAD

**Issue by Cylwen** [sillvva/rpg-schedule#208]
embed-user-tags can result in invalid user being displayed for a valid user

13 April 2020: Testing Android and also web app showed 1-2 invalid users / game.
13 April 2020: Testing  Windows app, 1 invalid user displayed every two games.

**Comment by sillvva** [comment]
Sorry for the late reply.

Yes. This is a known bug on Discord's end. I've added the option for people who want to use it regardless, but it is disabled by default for that exact reason. There's nothing I am aware of that I can do about it.

I mention this on the help page for that configuration option.
![image](https://user-images.githubusercontent.com/5138384/79525494-98461b80-8028-11ea-9bef-182f14ea0fbf.png)
