### ISSUE TITLE
Calendar is broken in Firefox

### ISSUE THREAD

**Issue by Demiko** [sillvva/rpg-schedule#215]
Calendar does not render while using latest Firefox release (desktop 75.0 and mobile 68.7.0).
Tested with add-ons disabled and with a clean a profile.

![Screenshot_2020-04-21 RPG Schedule](https://user-images.githubusercontent.com/1906483/79884922-97353580-83fe-11ea-881e-66595be5498a.png)

**Comment by sillvva** [comment]
Thanks! I will get a fix pushed out for this tonight.
