### ISSUE TITLE
[Feature Request] Google Calendar Feature Improvements

### ISSUE THREAD

**Issue by traek** [sillvva/rpg-schedule#229]
The current implementation of the Google Calendar links that are generated miss on two fronts for our group:

1. The start **and** end times of the Google Calendar entry are both set to the Game start time
2. If a game is set to repeat, the Google Calendar entry does not reflect that

Ideally the Google Calendar would exactly match the Game schedule. A nice-to-have list would include:

* *Auto-updating calendar items*. I realize this may require a bit of rework as it would need to be a full-on calendar rather than a simple entry. Again, in the nice-to-have list.
* *Invite specific users*. This would mean they would get a personal invite and automatically consume a slot but would not be confirmed (probably a new status) until they accept it. A decline would open up their reserved slot
* *Archiving past events*. For recurring events, it'd be nice to be able to see who accepted/attended events.

**Comment by sillvva** [comment]
1. This is fixed
2. This is fixed

- _Auto-updating calendar items._ I have tried to set up an iCalendar (.ics) file for linking RPG Schedule to calendars. However, Google Calendar never seems to pull updates to the events, even though the source file updates automatically. Microsoft Outlook does about once per hour.
- _Invite specific users._ I assume you're referring to inviting via Google and updating RPG Schedule accordingly. This is not something I can do without somehow being able to link Google and Discord accounts for each invitee.
- _Archiving past events._ I assume this is related to the above item, so it would have similar issues.

**Comment by traek** [comment]
First off, thanks for the fast work! Second, sorry I wasn't very clear on the other requests (since they were kind of pie-in-the-sky anyway):

Invite specific users: I mean to say Discord users. That way, I can reserve a spot but still require they respond. I know it's not far off from what you already have.
Archiving past events: this was having the ability to go back and see past events in Discord and see details like who attended. It'd be nice to be able to go back and remember who showed up, etc., especially for creating gaming logs after the fact (I'm doing D&D Adventurers League as one of our groups).

As far as Google Calendar is concerned, the only thing I'm concerned about is allowing people to use those links you create and have those reflect whatever RPG-Schedule is doing. I'll definitely use it myself but I expect everything to happen on the bot-side of things and not the other way around.

As a software developer, I prefer a single system of record and as far as I'm concerned, that's your bot.

**Comment by sillvva** [comment]
Ah, the reason why past events aren't available is due to the fact that the database is "currently" in free tier and the bot auto prunes old events from the database to conserve space.

Since I have started a Patreon, I will do some research on paid tiers to see if allowing users to configure their server to have longer prune intervals (like 1 year) is possible.

**Comment by traek** [comment]
Awesome, thanks!
