### ISSUE TITLE
[Question-ish] Do you want a dockerfile?

### ISSUE THREAD

**Issue by halkeye** [sillvva/rpg-schedule#243]
I created a dockerfile so I could run this on my cluster. Do you want a PR for it? I see your using heroku so wasn't sure if you'd use or want it.

**Comment by sillvva** [comment]
I don't currently have plans to use Docker. Plus, the website and the bot/api are now separated into separate repositories. So bundling this repo, would only get you the bot logic, but not the ui logic.

**Comment by halkeye** [comment]
Okay I'll try and keep https://hub.docker.com/r/halkeye/discord-rpg-schedule updated with master and add the UI repo
