### ISSUE TITLE
Game Posts Tagging Users Outside of Embeds

### ISSUE THREAD

**Issue by Melopod** [sillvva/rpg-schedule#244]
Since the update and the server restarts, the bot has been posting game posts as usual, but has been tagging users outside of the embed whenever anyone RSVPs (as well as the GM).
User tags are toggled off for the embed (I do not want to tag people to begin with) and toggling that on/off has not changed anything either (not that I was expecting it to).
Example attached.
![image](https://user-images.githubusercontent.com/51038503/83342211-5c49db80-a2a1-11ea-831f-f30eb7abd3ca.png)

**Comment by sillvva** [comment]
I plan to add a configuration option to turn it off shortly.
