### ISSUE TITLE
[Feature Request] Support Non-integer Timezones

### ISSUE THREAD

**Issue by 5310** [sillvva/rpg-schedule#50]
**Is your feature request related to a problem? Please describe.**
Currently, the web interface does not accept non-integer timezones. I'm from one of those awkward but no less real [timezones whose offsets are not neat round hours](https://www.timeanddate.com/time/time-zones-interesting.html) (UTC+0530 in my case, IST). I simply can't create game schedules at all.

**Describe the solution you'd like**
I would like to be able to either pick from a [list of all timezones](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets) or input fractional timezone offsets when creating games.

**Additional context**
I tried to fix the `games` view by adding `step=".25"` to the timezone input which would cover all the exotic timezones out there. But then the game gets created with invalid time as I notice the models try to `parseInt()` it. Oops!

**Comment by sillvva** [comment]
@5310 sorry for the delay. I didn't add the step=".25", but you should be able to enter it.

**Comment by 5310** [comment]
I just tried to make a new event by editing the form with `step=".25"`, the event got made, and since it didn't give an instant reminder, I assume it worked! Plus the edit link shows the fractional timezone value as well!

Aside from the `step` attribute on the form, it looks like the Discord embed would also need to be updated as it still shows `When: Invalid date (GMT+5.5)`.

**Comment by sillvva** [comment]
Added the step=".25" and fixed the invalid date issue.

**Comment by 5310** [comment]
Everything's working! :raised_hands: Thank you very much for the very prompt fix!
