### ISSUE TITLE
[Feature Request] Use Server nicknames on attendance lists

### ISSUE THREAD

**Issue by DonCarnohan** [sillvva/rpg-schedule#77]
On our server we have players change their discord names to include their character names, with this lacking it gets a bit confusing to organize who has signed up for what. A configuration option to display a user's nickname rather than their discord username would be a major improvement for our uses!

I'm not super familiar with the language or I'd attempt it myself. I might still give it a go, but curious what others think.

**Comment by DonCarnohan** [comment]
A possible alternative is to just use full @ tags for users, then discord will display the nickname.
Since these would be added via an edit for users signing up, it wouldn't ping the user, it would however show up in their recent mentions, which might be a positive. And users who are reserved will be pinged but again, being notified of an event which somebody else signed you up for might be a good thing.

**Comment by sillvva** [comment]
You can enable this by disabling the use of embeds with this command: `!schedule embeds off`

**Comment by DonCarnohan** [comment]
Oh, thanks for the info! Might be worth adding that to the Readme or something so it's more clear. 

Also, thanks for making this awesome tool, it's great
