### ISSUE TITLE
RPG Schedule not showing posted events for server

### ISSUE THREAD

**Issue by Protocol-Black** [sillvva/rpg-schedule#83]
Discord members unable to see scheduled events even if they have the scheduling role. Only admins can see roles. Not sure what issue is. [Screenshot](https://media.discordapp.net/attachments/633910450794266644/634846813387489291/unknown.png?width=1321&height=677)

**Comment by sillvva** [comment]
Are you setting the game times in the future? If so, the games should show up there for any user on the server, regardless of role.

Here is a link to my support Discord server. If you're still having issues, you can private message me an invite link to your Discord server from there. Then I can take a closer look at the issue.
https://discord.gg/mazZEe3
